### ISSUE TITLE
Unable to install missing an SConstruct file

### ISSUE THREAD

**Issue by globeone** [Tatsh/bpmdetect#3]
Am unable to find the SConstruct file to install the application. Would it be possible to publish one on here on GitHub, please?

~/gitProgrammas/bpmdetect/src

❭ scons

scons: *** No SConstruct file found.
File "/usr/lib/scons/SCons/Script/Main.py", line 940, in _main

**Comment by Tatsh** [comment]
This project in its latest version doesn't use SCons. It uses CMake.

I kept the old version in the v0.6.2 tag: https://github.com/Tatsh/bpmdetect/blob/v0.6.2/SConstruct
